// frontend/recipe-frontend/src/components/ui/Loading.vue
<template>
  <div class="flex flex-col items-center justify-center py-20 space-y-4">
    <div class="relative size-16">
      <div class="absolute inset-0 border-4 border-orange-100 rounded-full"></div>
      <div class="absolute inset-0 border-4 border-orange-500 rounded-full border-t-transparent animate-spin"></div>
    </div>
    <p v-if="message" class="text-gray-400 font-bold animate-pulse">{{ message }}</p>
  </div>
</template>

<script setup lang="ts">
defineProps<{ message?: string }>()
</script>

// chat-app/src/components/UI/Loading.tsx
import { Loader2 } from "lucide-react";
import { cx } from "./utils";

interface LoadingProps {
  label?: string;
  fullScreen?: boolean;
  className?: string;
  iconClassName?: string;
}

export default function Loading({
  label,
  fullScreen = false,
  className,
  iconClassName,
}: LoadingProps) {
  return (
    <div
      className={cx(
        "flex items-center justify-center",
        fullScreen ? "h-screen bg-slate-50" : "h-full w-full",
        className
      )}
    >
      <div className="flex flex-col items-center gap-3 text-center">
        <Loader2
          className={cx(
            "size-8 animate-spin text-slate-900",
            iconClassName
          )}
        />
        {label ? (
          <span className="text-sm font-medium text-blue-900">{label}</span>
        ) : null}
      </div>
    </div>
  );
}
