// practical-17/frontend/src/auth/Login.vue
<template>
  <section class="min-h-screen bg-[#f8f6f3] flex items-center justify-center px-4">
    <div class="w-full max-w-md">
      
      <div class="bg-white rounded-3xl shadow-xl p-10 border border-olive-100 animate-fade-in">
        
        <div class="text-center mb-8">
          <h1 class="text-4xl font-light tracking-widest text-olive-700">
            StyleSphere
          </h1>
          <p class="text-sm text-gray-500 mt-2 tracking-wide">
            Welcome back to your style
          </p>
        </div>

        <div v-if="error" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
          <p class="text-sm text-red-600">{{ error }}</p>
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-6">

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Email Address
            </label>
            <input
              v-model="formData.email"
              type="email"
              placeholder="Enter your email"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-500 focus:border-olive-500 transition-all outline-none"
              :class="{ 'border-red-500': errors.email }"
              required
            />
            <p v-if="errors.email" class="mt-1 text-sm text-red-500">{{ errors.email }}</p>
          </div>

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Password
            </label>
            <input
              v-model="formData.password"
              type="password"
              placeholder="Enter your password"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-500 focus:border-olive-500 transition-all outline-none"
              :class="{ 'border-red-500': errors.password }"
              required
            />
            <p v-if="errors.password" class="mt-1 text-sm text-red-500">{{ errors.password }}</p>
          </div>
 

          <button
            type="submit"
            :disabled="loading"
            class="w-full py-3 bg-olive-600 text-white rounded-xl font-medium tracking-wide hover:bg-olive-700 transition-all duration-300 hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {{ loading ? 'Signing in...' : 'Sign In' }}
          </button>

        </form>

        <div class="my-8 flex items-center">
          <div class="flex-1 h-px bg-gray-200"></div>
          <span class="px-4 text-gray-400 text-sm">OR</span>
          <div class="flex-1 h-px bg-gray-200"></div>
        </div>

        <p class="text-center text-sm text-gray-600">
          New to StyleSphere?
          <router-link to="/register" class="text-olive-700 font-medium hover:underline ml-1">
            Create an Account
          </router-link>
        </p>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';

const router = useRouter();
const authStore = useAuthStore();

const formData = ref({
  email: '',
  password: '',
});

const errors = ref<Record<string, string>>({});
const loading = ref(false);
const error = ref('');

const validateForm = () => {
  errors.value = {};
  
  if (!formData.value.email) {
    errors.value.email = 'Email is required';
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.value.email)) {
    errors.value.email = 'Please enter a valid email';
  }
  
  if (!formData.value.password) {
    errors.value.password = 'Password is required';
  }
  
  return Object.keys(errors.value).length === 0;
};

const handleSubmit = async () => {
  if (!validateForm()) return;
  
  loading.value = true;
  error.value = '';
  
  const success = await authStore.login(formData.value.email, formData.value.password);
  
  if (success) {
    if (authStore.isAdmin) {
      router.push('/admin/dashboard')
    } else {
      router.push({ name: 'Home' })
    }
  } else {
    error.value = authStore.error || 'Login failed. Please try again.';
  }
  
  loading.value = false;
};
</script>

<style scoped>
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-in {
  animation: fadeIn 0.8s ease forwards;
}
</style>

// chat-app/src/pages/Login.tsx
import { loginUser } from "../firebase/auth";
import { Link } from "react-router-dom";
import { validateEmail, validatePassword } from "../utils/validation";
import { Input } from "../components/UI/Input";
import Button from "../components/UI/Button";
import { useAuthForm } from "../hooks/useAuthForm";
import { Mail, Lock } from "lucide-react"

export function Login() {
  const { values, errors, setErrors, loading, setLoading, handleChange } = useAuthForm({
    email: "",
    password: "",
  });

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    const emailError = validateEmail(values.email);
    const passwordError = validatePassword(values.password);

    if (emailError || passwordError) {
      setErrors({ email: emailError, password: passwordError });
      return;
    }

    try {
      setLoading(true);
      await loginUser(values.email, values.password);
    } catch {
      alert("Invalid email or password");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
      <div className="max-w-md w-full space-y-8 bg-white p-10 rounded-xl shadow-lg">
        <div className="text-center">
          <h2 className="text-3xl font-extrabold text-gray-900">Welcome back</h2>
          <p className="mt-2 text-sm text-gray-600">Please sign in to your account</p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleLogin}>
          <div className="space-y-4">
            <Input label="Email Address" type="email" placeholder="name@example.com" value={values.email} error={errors.email}
              icon={<Mail className="w-5 h-5 text-gray-400" />}
              onChange={(e) => handleChange("email", e.target.value)}
            />

            <Input label="Password" type="password" placeholder="••••••••" value={values.password} error={errors.password}
              icon={<Lock className="w-5 h-5 text-gray-400" />}
              onChange={(e) => handleChange("password", e.target.value)}
            />
          </div>

          <Button type="submit" variant="primary" className="w-full"
            disabled={loading}
          >
            {loading ? "Logging in..." : "Login"}
          </Button>
        </form>
        <div className="text-center text-sm">
          <p className="text-gray-600">
            Don't have an account? <Link to="/register" className="text-blue-600">Register here</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
