// practical-18/frontend/src/pages/auth/Register.vue
<template>
  <section class="min-h-screen bg-[#f8f6f3] flex items-center justify-center px-4 py-8">
    <div class="w-full max-w-md">
      
      <div class="bg-white rounded-3xl shadow-xl p-10 border border-olive-100 animate-fade-in">
        
        <div class="text-center mb-8">
          <h1 class="text-4xl tracking-widest text-olive-700">
            StyleSphere
          </h1>
          <p class="text-sm text-gray-600 mt-2 tracking-wide">
            Create your account
          </p>
        </div>

        <div v-if="error" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
          <p class="text-sm text-red-600">{{ error }}</p>
        </div>

        <div v-if="successMessage" class="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg">
          <p class="text-sm text-green-600">{{ successMessage }}</p>
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-5">

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Full Name
            </label>
            <input
              v-model.trim="formData.name"
              type="text"
              placeholder="Enter your full name"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-600 focus:border-olive-600 transition-all outline-none"
              :class="{ 'border-red-500': errors.name }"
              minlength="2"
              maxlength="50"
              autocomplete="name"
            />
            <p v-if="errors.name" class="mt-1 text-sm text-red-500">{{ errors.name }}</p>
          </div>

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Email Address
            </label>
            <input
              v-model.trim="formData.email"
              type="email"
              placeholder="Enter your email"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-600 focus:border-olive-600 transition-all outline-none"
              :class="{ 'border-red-500': errors.email }"
              maxlength="100"
              autocomplete="email"
            />
            <p v-if="errors.email" class="mt-1 text-sm text-red-500">{{ errors.email }}</p>
          </div>

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Password
            </label>
            <input
              v-model="formData.password"
              type="password"
              placeholder="Create a password"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-600 focus:border-olive-600 transition-all outline-none"
              :class="{ 'border-red-500': errors.password }"
              minlength="8"
              maxlength="64"
              autocomplete="new-password"
            />
            <p v-if="errors.password" class="mt-1 text-sm text-red-500">{{ errors.password }}</p>
          </div>

          <div>
            <label class="block text-sm text-gray-600 mb-2 tracking-wide">
              Confirm Password
            </label>
            <input
              v-model="formData.confirmPassword"
              type="password"
              placeholder="Confirm your password"
              class="w-full px-4 py-3 border border-olive-300 rounded-xl focus:ring-2 focus:ring-olive-600 focus:border-olive-600 transition-all outline-none"
              :class="{ 'border-red-500': errors.confirmPassword }"
              minlength="8"
              maxlength="64"
              autocomplete="new-password"
            />
            <p v-if="errors.confirmPassword" class="mt-1 text-sm text-red-500">{{ errors.confirmPassword }}</p>
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="w-full py-3 bg-olive-600 text-white rounded-xl font-medium tracking-wide hover:bg-olive-700 transition-all duration-300 hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {{ loading ? 'Creating account...' : 'Create Account' }}
          </button>

        </form>

        <div class="my-8 flex items-center">
          <div class="flex-1 h-px bg-gray-200"></div>
          <span class="px-4 text-gray-400 text-sm">OR</span>
          <div class="flex-1 h-px bg-gray-200"></div>
        </div>

        <p class="text-center text-sm text-gray-600">
          Already have an account?
          <router-link to="/login" class="text-olive-700 font-medium hover:underline ml-1">
            Sign In
          </router-link>
        </p>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '@/store/auth';
import { normalizeEmail, normalizeName, validateRegisterForm } from '@/utils/validators';

const router = useRouter()
const authStore = useAuthStore()

const formData = ref({
  name: '',
  email: '',
  password: '',
  confirmPassword: '',
})

const errors = ref<Record<string, string>>({});
const loading = ref(false);
const error = ref('');
const successMessage = ref('');

const validateForm = () => {
  errors.value = validateRegisterForm(formData.value);
  return Object.keys(errors.value).length === 0;
};

const handleSubmit = async () => {
  if (!validateForm()) return

  loading.value = true
  error.value = ''
  successMessage.value = ''

  const sanitizedName = normalizeName(formData.value.name);
  const normalizedEmail = normalizeEmail(formData.value.email);

  const success = await authStore.registerUser(
    sanitizedName,
    normalizedEmail,
    formData.value.password,
  );
  
  if (success) {
    successMessage.value = 'Account created successfully! Redirecting...'
    router.push('/')
  } else {
    error.value = authStore.error || 'Registration failed. Please try again.'
  }
  
  loading.value = false;
};
</script>

// chat-app/src/pages/Register.tsx
import { registerUser } from "../firebase/auth";
import { db } from "../firebase/config";
import { setDoc, doc, serverTimestamp } from "firebase/firestore";
import { Link } from "react-router-dom";
import { validateName, validateEmail, validatePassword, validateConfirmPassword } from "../utils/validation";
import { Input } from "../components/UI/Input";
import Button from "../components/UI/Button";
import { useAuthForm } from "../hooks/useAuthForm";
import { Mail, User, Lock } from "lucide-react"

export default function Register() {
  const { values, errors, setErrors, loading, setLoading, handleChange } = useAuthForm({
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors = {
      name: validateName(values.name),
      email: validateEmail(values.email),
      password: validatePassword(values.password),
      confirmPassword: validateConfirmPassword(values.password, values.confirmPassword),
    };

    if (Object.values(newErrors).some((err) => err)) {
      setErrors(newErrors as any);
      return;
    }

    try {
      setLoading(true);
      const res = await registerUser(values.email, values.password);
      await setDoc(doc(db, "users", res.user.uid), {
        uid: res.user.uid,
        email: res.user.email,
        name: values.name || "New User",
        photoURL: "",
        createdAt: serverTimestamp(),
      });
      alert("User Registered Successfully");
    } catch (err: any) {
      alert(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
      <div className="max-w-md w-full space-y-6 bg-white p-10 rounded-xl shadow-lg">
        <div className="text-center">
          <h2 className="text-3xl font-extrabold text-gray-900">Create Account</h2>
          <p className="mt-2 text-sm text-gray-600">Join the community today</p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleRegister}>
          <div className="space-y-4">
            <Input label="Full Name" type="text" placeholder="Your name" value={values.name} error={errors.name}
              icon={<User className="w-5 h-5 text-gray-400" />} 
              onChange={(e) => handleChange("name", e.target.value)}
            />
            <Input label="Email Address" type="email" placeholder="name@example.com" value={values.email} error={errors.email}
              icon={<Mail className="w-5 h-5 text-gray-400" />}
              onChange={(e) => handleChange("email", e.target.value)}
            />
            <Input label="Password" type="password" placeholder="••••••••" value={values.password} error={errors.password}
              icon={<Lock className="w-5 h-5 text-gray-400" />}
              onChange={(e) => handleChange("password", e.target.value)}
            />
            <Input label="Confirm Password" type="password" placeholder="••••••••" value={values.confirmPassword} error={errors.confirmPassword}
              icon={<Lock className="w-5 h-5 text-gray-400" />}
              onChange={(e) => handleChange("confirmPassword", e.target.value)}
            />
          </div>

          <Button type="submit" variant="primary" className="w-full"
            disabled={loading}
          >
            {loading ? "Creating..." : "Register"}
          </Button>
        </form>

        <div className="text-center text-sm">
          <p className="text-gray-600">
            Already have an account? <Link to="/" className="text-blue-600">Sign in</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
