// frontend/recipe-frontend/src/components/ui/Modal.vue
<template>
  <div 
    v-if="isOpen" 
    class="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4" 
    @click.self="$emit('close')"
  >
    <div class="bg-neutral-800 rounded-3xl p-8 max-w-md w-full max-h-[90vh] overflow-y-auto shadow-2xl">
      
      <div class="flex items-center justify-between mb-6">
        <h3 class="text-2xl font-black text-gray-100 tracking-tight">
          {{ title }}
        </h3>
        <button 
          @click="$emit('close')" 
          class="p-2 -m-2 text-gray-300 hover:text-gray-100 rounded-xl cursor-pointer transition-all hover:bg-neutral-600"
        >
          <span class="text-2xl">&times;</span>
        </button>
      </div>

      <slot></slot>

      <div class="flex gap-3">
        <button 
          @click="$emit('close')" 
          class="flex-1 px-6 py-3 text-gray-100 font-bold border border-gray-200 rounded-xl cursor-pointer hover:bg-neutral-600 transition-all"
        >
          {{ cancelText || 'Cancel' }}
        </button>
        <button 
          @click="$emit('confirm')" 
          :disabled="confirmDisabled" 
          class="flex-1 px-6 py-3 bg-gradient-to-r from-orange-500 to-orange-400  hover:bg-orange-600 text-white font-bold rounded-xl cursor-pointer transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          <span v-if="loading" class="animate-spin">⚙️</span>
          <span>{{ confirmText || 'Confirm' }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  isOpen: boolean
  title: string
  confirmDisabled?: boolean
  confirmText?: string
  cancelText?: string
  loading?: boolean 
}>()

defineEmits<{
  close: []
  confirm: []
}>()
</script>

// practical-20/src/components/ui/Modal.tsx
import React, { useEffect } from 'react';

type ModalProps = React.PropsWithChildren<{
  open: boolean;
  title: string;
  subtitle?: string;
  onClose: () => void;
  footer?: React.ReactNode;
  maxWidthClassName?: string;
}>;

export const Modal: React.FC<ModalProps> = ({
  open,
  title,
  subtitle,
  onClose,
  children,
  footer,
  maxWidthClassName = 'max-w-2xl',
}) => {
  useEffect(() => {
    if (!open) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [open, onClose]);

  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50">
      <button
        aria-label="Close dialog"
        className="absolute inset-0 h-full w-full bg-black/50 backdrop-blur-sm transition-opacity"
        onClick={onClose}
        type="button"
      />
      <div className="relative mx-auto flex min-h-dvh items-center justify-center p-4">
        <div
          role="dialog"
          aria-modal="true"
          className={[
            'w-full',
            maxWidthClassName,
            'overflow-hidden rounded-2xl border border-teal-100/30 bg-neutral-700 shadow-2xl ring-1 ring-white/5',
          ].join(' ')}
        >
          <div className="border-b border-white/10 px-6 py-5">
            <div className="text-xl font-bold text-white">{title}</div>
            {subtitle ? <div className="mt-1 text-sm text-white/60">{subtitle}</div> : null}
          </div>
          <div className="px-6 py-6">{children}</div>
          {footer ? (
            <div className="border-t border-white/10 px-6 py-4 bg-black/10">
              {footer}
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
};
